#!/bin/bash

function _fzf_compgen_path {
    fdfind --hidden --follow --exclude ".git" . "$1"
}

function _fzf_compgen_dir {
    fdfind --type d --hidden --follow --exclude ".git" . "$1"
}

source /usr/share/doc/fzf/examples/key-bindings.bash
#source /usr/share/doc/fzf/examples/completion.bash

if type rg &> /dev/null; then
    export FZF_DEFAULT_COMMAND='fdfind'
    export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
    #export FZF_DEFAULT_COMMAND='rg --files'
    #export FZF_DEFAULT_COMMAND='grep --files'
    export FZF_DEFAULT_OPTS='-m --height 50% --border'
fi
