#!/bin/bash

set -o vi # Vi mode.

bind '"\C-p":history-search-backward'
bind '"\C-n":history-search-forward'

export PATH="$PATH:/opt/nvim-linux64/bin"

export EDITOR=nvim

export DENO_INSTALL="/home/maximilian/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

#export ONE_CUSTOM_REPO=/home/maximilian/Workspace/custom
