#!/bin/bash

if type rg &> /dev/null; then
    export FZF_DEFAULT_COMMAND='fdfind'
    export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
    #export FZF_DEFAULT_COMMAND='rg --files'
    #export FZF_DEFAULT_COMMAND='grep --files'
    export FZF_DEFAULT_OPTS='-m --height 50% --border'
fi
